package com.outleap.demo.lock

import org.springframework.stereotype.Component

@Component
class ConcurrencyHelper {

    fun getLockKey(context: ConcurrencyContext, name: Any) = "${context.prefix}_$name"
}

enum class ConcurrencyContext(val prefix: String) {
    GB_STUDENT_DOCUMENT("GB_STUDENT_DOCUMENT"),
    SCHOLAR_STUDENT_DOCUMENT("SCHOLAR_STUDENT_DOCUMENT"),
    GB_STUDENT("GB_STUDENT"),
    GB_APPLICATION("GB_APPLICATION"),
    GB_USER("GB_USER"),
    GB_APPLICATION_DOCUMENT("GB_APPLICATION_DOCUMENT"),
    SCHOLAR_APPLICATION_DOCUMENT("SCHOLAR_APPLICATION_DOCUMENT"),
    GB_SCHOLAR_APPLICATION("GB_SCHOLAR_APPLICATION"),
    GB_SCHOLAR_EXAM_INFO("GB_SCHOLAR_EXAM_INFO"),
    GB_VISA_APPLICATION("GB_VISA_APPLICATION"),
    APPLICATION_ASSIGNMENT("APPLICATION_ASSIGNMENT"),
    DEFERRAL("DEFERRAL"),
    TASK_ASSIGNMENT("TASK_ASSIGNMENT"),
    PAYMENT_DOCUMENT("PAYMENT_DOCUMENT"),
    GB_SCHOLAR_APPLICATION_PRIORITY("GB_SCHOLAR_APPLICATION_PRIORITY"),
    GB_APPLICATION_PAYMENT_UPDATE("GB_APPLICATION_PAYMENT_UPDATE"),
    DOCUMENT_UPDATE("DOCUMENT_UPDATE"),
    SIXTH_SENSE_TOKEN("SIXTH_SENSE_TOKEN"),
    GB_ACCOMMODATION_REQUEST("GB_ACCOMMODATION_REQUEST"),
    GB_PAYMENT_REQUEST("GB_PAYMENT_REQUEST"),
    GB_VAS_REQUEST("GB_VAS_REQUEST"),
    GTE_APPLICATION("GTE_APPLICATION"),
    GB_GIC_REQUEST("GB_GIC_REQUEST"),
    GB_LOAN_REQUEST("GB_LOAN_REQUEST"),
    SUB_AGENT("SUB_AGENT"),
    STUDENT_LOGIN("STUDENT_LOGIN"),
    STUDENT_ENGAGEMENT("STUDENT_ENGAGEMENT"),
    GB_VOUCHER_ORDER("GB_VOUCHER_ORDER")
}